#!/bin/bash
echo Estos son los parametros recibidos: $*
FILES='/home/patu/Downloads/ObservatorioCIEC-master/media/csv/*'
user='root'
pass='root'
db='OESE'
for f in $FILES
do
    if [ "$1" == "comercio_cgce" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_ciiu3" ]; then
            mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_cpc" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_cuode" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_equivalencia" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (nandina,cpc,cuode,cgce,sistema_armotizado,ciiu3,cuci3)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_nandina" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (subpartida,descripcion)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_paises" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,pais)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_export_nandina" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (ano,mes,pais,subpartida_nandina,peso,fob)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_import_nandina" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (ano,mes,pais,subpartida_nandina,peso,fob,cif)"  -u$user -p$pass $db --local-infile
    elif [ "$1" == "comercio_export_total" ]; then
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (ano,mes,fob,peso)"  -u$user -p$pass $db --local-infile
    else
        mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (ano,mes,fob,cif,peso)"  -u$user -p$pass $db --local-infile
    fi
done
rm -f $FILES