#!/bin/bash
echo Estos son los parametros recibidos: $*
FILES='/home/patu/Downloads/ObservatorioCIEC-master/media/csv/*'
for f in $FILES
do
	if [ "$1" == "comercio_cgce" ]; then
		mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -uroot -proot OESE --local-infile
	elif [ "$1" == "comercio_ciiu3" ]; then
    	mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -uroot -proot OESE --local-infile
    elif [ "$1" == "comercio_cpc" ]; then
    	mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -uroot -proot OESE --local-infile
    elif [ "$1" == "comercio_cuode" ]; then
    	mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,descripcion)"  -uroot -proot OESE --local-infile
    elif [ "$1" == "comercio_equivalencia" ]; then
    	mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (nandina,cpc,cuode,cgce,sistema_armotizado,ciiu3,cuci3)"  -uroot -proot OESE --local-infile
    elif [ "$1" == "comercio_nandina" ]; then
		mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (subpartida,descripcion)"  -uroot -proot OESE --local-infile
    else
		mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (codigo,pais)"  -uroot -proot OESE --local-infile
    fi
done
rm -f $FILES