#!/bin/bash
echo Estos son los parametros recibidos: $*
FILES='/home/patu/Downloads/ObservatorioCIEC-master/media/csv/*'
user='root'
pass='root'
db='OESEdb'
for f in $FILES
do
    mysql -e "load data local infile '"$f"' into table $1 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES (anio,trimestre,area,region_natural,ciudad_ind,fexp,genero,edad,etnia,edad_group,nivinst,anosaprob,pet,pei,pea,ocupa,onocla,oplenos,suboc,suboc1,suboc2,deso,deso1,deso2,deaboc1,deaboc2,sect_formal,sect_informal,sect_srvdom,sect_moderno,sect_agricola,sub_inv,sub_informal,ingrl,rama_act_1,rama_act_2,grupo_ocup_1,seguro,satis_laboral,descon_bajos_ingresos,descon_horarios,descon_estabil,descon_amb_laboral,descon_activ,experiencia,migracion_extranjera,migracion_rural_urbano,tamano_hogar,hogar_noFamiliar,hogar_completo,ingreso_hogar,part_quehaceres,horas_part_quehaceres,categ_ocupa,condact,tipo_ocupa,tipo_deso,rela_jef,analfabeta,nocla,ultimos_anios,condInact,rentista,jubil,estudiant,amaCasa,incapacit,otro)"  -u$user -p$pass Sdb --local-infile
done
	mysql -e "UPDATE $1 set sectorEmpleo = NULL WHERE char_length(sectorEmpleo) = 1;" -u$user -p$pass $db
rm -f $FILES