from django.db import models
from disintegrations.models import Type
from django.contrib import messages
from django.core.validators import MaxValueValidator, MinValueValidator


class Data_from_2003_4(models.Model):
    anio = models.PositiveSmallIntegerField()
    trimestre = models.PositiveSmallIntegerField()
    area = models.CharField(max_length=10, null=True)
    region_natural = models.CharField(max_length=15, null=True)
    ciudad_ind = models.CharField(max_length=15, null=True)
    fexp = models.DecimalField(decimal_places=4, max_digits=7, null=True)
    genero = models.CharField(max_length=10, null=True)
    edad = models.PositiveSmallIntegerField()
    etnia = models.CharField(max_length=15, null=True)
    edad_group = models.CharField(max_length=10, null=True)
    nivinst = models.CharField(max_length=30, null=True)
    anosaprob = models.PositiveSmallIntegerField(null=True)
    pet = models.NullBooleanField()
    pei = models.NullBooleanField()
    pea = models.NullBooleanField()
    ocupa = models.NullBooleanField()
    onocla = models.NullBooleanField()
    oplenos = models.NullBooleanField()
    suboc = models.NullBooleanField()
    suboc1 = models.NullBooleanField()
    suboc2 = models.NullBooleanField()
    deso = models.NullBooleanField()
    deso1 = models.NullBooleanField()
    deso2 = models.NullBooleanField()
    deaboc1 = models.NullBooleanField()
    deaboc2 = models.NullBooleanField()
    sect_formal = models.NullBooleanField()
    sect_informal = models.NullBooleanField()
    sect_srvdom = models.NullBooleanField()
    sect_moderno = models.NullBooleanField()
    sect_agricola = models.NullBooleanField()
    sub_inv = models.NullBooleanField()
    sub_informal = models.NullBooleanField()
    ingrl = models.PositiveIntegerField(null=True)
    rama_act_1 = models.CharField(max_length=75, null=True)
    rama_act_2 = models.CharField(max_length=75, null=True)
    grupo_ocup_1 = models.CharField(max_length=75, null=True)
    seguro = models.CharField(max_length=50, null=True)
    migracion = models.CharField(max_length=2, null=True)

    class Meta:
        verbose_name = "un dato desde 2003 - 4"
        verbose_name_plural = "Datos desde 2003 - 4"


class Data_from_2007_2(models.Model):
    anio = models.PositiveSmallIntegerField()
    trimestre = models.PositiveSmallIntegerField()
    area = models.CharField(max_length=10, null=True)
    region_natural = models.CharField(max_length=15, null=True)
    ciudad_ind = models.CharField(max_length=15, null=True)
    fexp = models.DecimalField(decimal_places=4, max_digits=7, null=True)
    genero = models.CharField(max_length=10, null=True)
    edad = models.PositiveSmallIntegerField()
    etnia = models.CharField(max_length=15, null=True)
    edad_group = models.CharField(max_length=10, null=True)
    nivinst = models.CharField(max_length=30, null=True)
    anosaprob = models.PositiveSmallIntegerField(null=True)
    pet = models.NullBooleanField()
    pei = models.NullBooleanField()
    pea = models.NullBooleanField()
    ocupa = models.NullBooleanField()
    onocla = models.NullBooleanField()
    oplenos = models.NullBooleanField()
    suboc = models.NullBooleanField()
    suboc1 = models.NullBooleanField()
    suboc2 = models.NullBooleanField()
    deso = models.NullBooleanField()
    deso1 = models.NullBooleanField()
    deso2 = models.NullBooleanField()
    deaboc1 = models.NullBooleanField()
    deaboc2 = models.NullBooleanField()
    sect_formal = models.NullBooleanField()
    sect_informal = models.NullBooleanField()
    sect_srvdom = models.NullBooleanField()
    sect_moderno = models.NullBooleanField()
    sect_agricola = models.NullBooleanField()
    sub_inv = models.NullBooleanField()
    sub_informal = models.NullBooleanField()
    ingrl = models.PositiveIntegerField(null=True)
    rama_act_1 = models.CharField(max_length=75, null=True)
    rama_act_2 = models.CharField(max_length=75, null=True)
    grupo_ocup_1 = models.CharField(max_length=75, null=True)
    seguro = models.CharField(max_length=50, null=True)
    migracion = models.CharField(max_length=2, null=True)

    class Meta:
        verbose_name = "un dato desde 2007 - 2"
        verbose_name_plural = "Datos desde 2007 - 2"